version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  backend:
    build: 
      context: .
      target: backend
    ports:
      - 3000:3000
  frontend:
    build:
      context: .
      target: build-serve 
    ports:
      - 8080:8080